### ISSUE TITLE
这个项目没做完啊，现在还不能用。

### ISSUE THREAD

**Issue by yinchunlong** [kbengine/kbengine_ue4_plugins#2]
c++没有反射机制，InterfaceXX不好做，我熟悉ue4，可以参与ue4插件的开发，只是不熟悉kbengine, 请问下作者的关于ue4插件的开发计划是怎么样的(时间，技术要点).

**Comment by kbengine** [comment]
发了版本才可用。
计划就是尽可能翻译u3d插件，并尽可能降低ue4依赖，以后可能成为c++插件基础模版。

没有时间限制

**Comment by marshal-it** [comment]
目前还不是正式版？，你使用插件之后，Project Source代码下不能直接引用它的头文件，只能是Class下的！是否有这个问题？

**Comment by kbengine** [comment]
等版本

**Comment by kbengine** [comment]
你要引用什么头文件？

**Comment by marshal-it** [comment]
依托了Actor和Component应该没问题

**Comment by marshal-it** [comment]
我已经搭建好了，目前版本，连接KBE服务器没问题，我测试下通信！

**Comment by kbengine** [comment]
还没提交完， 先别用。
源码不全

**Comment by marshal-it** [comment]
OK。。。谢谢提醒！

**Comment by kbengine** [comment]
https://github.com/kbengine/kbengine_ue4_demo
可测试了，目前没有发布版本，服务端和客户端都使用git clone得到开发版本测试
