### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by sun1284065663** [kbengine/kbengine_ue4_plugins#37]
1>D:\KBProTestV_22_3\Plugins\KBEnginePlugins\Source\KBEnginePlugins\Private\DataTypes.cpp(396): error C2039: “readUint64”: 不是“MemoryStream”的成员
1>  D:\KBProTestV_22_3\Plugins\KBEnginePlugins\Source\KBEnginePlugins\Public\DataTypes.h(8): note: 参见“MemoryStream”的声明
1>D:\KBProTestV_22_3\Plugins\KBEnginePlugins\Source\KBEnginePlugins\Private\DataTypes.cpp(397): error C2039: “readInt32”: 不是“MemoryStream”的成员
1>  D:\KBProTestV_22_3\Plugins\KBEnginePlugins\Source\KBEnginePlugins\Public\DataTypes.h(8): note: 参见“MemoryStream”的声明
1>D:\KBProTestV_22_3\Plugins\KBEnginePlugins\Source\KBEnginePlugins\Private\DataTypes.cpp(398): error C2039: “readUint16”: 不是“MemoryStream”的成员
1>  D:\KBProTestV_22_3\Plugins\KBEnginePlugins\Source\KBEnginePlugins\Public\DataTypes.h(8): note: 参见“MemoryStream”的声明
1>D:\KBProTestV_22_3\Plugins\KBEnginePlugins\Source\KBEnginePlugins\Private\DataTypes.cpp(399): error C2039: “readUint16”: 不是“MemoryStream”的成员
1>  D:\KBProTestV_22_3\Plugins\KBEnginePlugins\Source\KBEnginePlugins\Public\DataTypes.h(8): note: 参见“MemoryStream”的声明
1>D:\KBProTestV_22_3\Plugins\KBEnginePlugins\Source\KBEnginePlugins\Public\Entity.h(342): error C2593: “operator =”不明确

**Comment by kebiao** [comment]
https://github.com/kbengine/kbengine_ue4_demo/blob/master/README_CN.md
