### ISSUE TITLE
 Unrecognized type 'int' - type must be a UCLASS, USTRUCT or UENUM

### ISSUE THREAD

**Issue by marshal-it** [kbengine/kbengine_ue4_plugins#6]
1>多个地方出现---如果用到蓝图的宏的话，必须用虚幻自己的数据类型，这个不能直接用int -- 可以用int32
  E:/GitHub/kbengine_ue4_demo/Plugins/kbengine_ue4_plugins/Source/KBEnginePlugins/Public/KBEvent.h(269) : Unrecognized type 'int' - type must be a UCLASS, USTRUCT or UENUM

UCLASS(Blueprintable, BlueprintType)
class KBENGINEPLUGINS_API UKBEventData_onLoseControlledEntity : public UKBEventData
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = KBEngine)
	int entityID;
};

int entityID; -> int32 entityID;

目前测试版本是UE4 4.10

**Comment by marshal-it** [comment]
貌似，4.14之后没有这个问题，4.10有点久远了

**Comment by kbengine** [comment]
可以关了？
