### ISSUE TITLE
KBEngineApp::destroy()报错

### ISSUE THREAD

**Issue by RPG3D** [kbengine/kbengine_ue4_plugins#8]
1.1.0版
destroy()调用到resetMessage的时候delete 了EntityDef::datatypes里面的值, 但是这个datatypes里面的值并不全是new出来的,在KBEngine::createDataFromStream() 里面最后一个else  判定里面有问题
```
KBEDATATYPE_BASE* val = NULL;
if (EntityDef::datatypes.Contains(name))
	val = EntityDef::datatypes[name];

EntityDef::datatypes.Add(valname, val);
```

**Comment by kebiao** [comment]
以后所有的插件都是通过工具生成的， 目前的插件提到的地方都会静态化生成。
https://github.com/kbengine/kbengine/tree/master/kbe/src/server/tools/kbcmd

**Comment by kebiao** [comment]
fixed
